# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/exynos7870-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a6lte,$(TARGET_DEVICE)),)

endif
